### ISSUE TITLE
使用SS码检索提示错误

### ISSUE THREAD

**Issue by xue1122** [Hellohistory/DX2_5#2]
在使用SS码进行检索书籍时会提示”Internal Server Error”这个错误异常
![error2](https://github.com/Hellohistory/DX2_5/assets/64252241/5807d2c0-0646-436f-957a-d4a70cf68fd3)

**Comment by Hellohistory** [comment]
写查询语句的时候没注意写岔了，已修复该bug，直接下载新的app.py替换原来的app.py就可以正常运行了
